version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - ENV=dev
      - DATABASE_URL=sqlite:///./data/insurance.db
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
